### ISSUE TITLE
clean up data for presentation

### ISSUE THREAD

**Issue by l00mi** [zazuko/alod#19]
- [x]  (we ideally need an entry for every archive on top of the hierarchy (with has-part))
- [x]  we need entries for the ISIL (agencyCode) with a real name (of the archive)
- [x]  we need to add manually an entry for every fonds (in total 5-10) on top of the hierarchy (with has-part)
- [x]  some dates are clearly bogus (> year 3333)
- [x] cleanup `related` vs `relation`

**Comment by l00mi** [comment]
@ktk Do we have the cleaned data also in the current fuseki?

**Comment by l00mi** [comment]
@ktk can you please take care of the open once?

**Comment by ktk** [comment]
@l00mi ok will try. Where is the ISIL list?

**Comment by l00mi** [comment]
I have it local for now.. will make a repo for it soon. Ideally you publish it with its own small trifid under isil.ch

[isil_20160503.n3.zip](https://github.com/zazuko/alod/files/967560/isil_20160503.n3.zip)

**Comment by ktk** [comment]
* `relation`: http://data.ge.alod.ch/id/archivalresource/adl-b-6771-a
* `related`: http://data.vs.alod.ch/id/archivalressource/CH_AEV-H_9.99

Correct is http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-relation

**Comment by ktk** [comment]
All done by now
