### ISSUE TITLE
Change the SPARQL query that every entry has the hierarchy to the top element available

### ISSUE THREAD

**Issue by l00mi** [zazuko/alod#48]
Every found document should also deliver all triples in the hierarchy up.

Lets say Item is the document shown in the interface:

Fonds -> Series -> (Item)

We need the necessary triples: Title, hasPart, and type (on top of my head not checked real name).

**Comment by l00mi** [comment]
http://purl.org/dc/elements/1.1/relation

**Comment by bergos** [comment]
@l00mi Hierarchy is now sent with the result list and an array is built in the renderer with [this commit](https://github.com/zazuko/zack-search/commit/d370dae83d4309a74f4f0c0ef6cab215baa6386a).

**Comment by l00mi** [comment]
Cool thanks, that is a good first approach, did you try with property paths? Because this is kinda a bit static, we might have much more levels than just 4 ...

**Comment by l00mi** [comment]
@bergos thanks
