### ISSUE TITLE
Change the order by age of document in the search results.

### ISSUE THREAD

**Issue by l00mi** [zazuko/alod#49]
Especially if there is no keyword the order should not be random but by e.g. age of document.

This might be tricky as the graph does not have an explicit order. Not sure if defined, but I guess if the sparql store has an orderby sub SELECT query the CONSTRUCT query might be ordered too..

To find out.

**Comment by l00mi** [comment]
http://www.w3.org/2006/time#intervalStarts

**Comment by bergos** [comment]
Maybe it works by using a ORDER BY on the highest level SELECT by score and intervalStarts.

**Comment by bergos** [comment]
@l00mi It works with a SELECT query, but the CONSTRUCT query destroys the order. I tried the following queries.

SELECT:
```
PREFIX : <http://voc.zazuko.com/zack#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  text: <http://jena.apache.org/text#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * {
  {
    SELECT ?sub ?score ?starts WHERE {
      ?sub <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.archiveshub.ac.uk/def/ArchivalResource> .
      OPTIONAL {
        ?sub <http://www.w3.org/2006/time#intervalStarts> ?starts .
      }
    }
    ORDER BY ?starts ?score
    OFFSET 0
    LIMIT 20
  }
  GRAPH ?g {
    ?sub ?pred ?obj .
  }
}
```

CONSTRUCT:
```
PREFIX : <http://voc.zazuko.com/zack#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  text: <http://jena.apache.org/text#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  :query :result ?sub .
  ?sub a :resultItem .
  ?sub ?pred ?obj .
  ?sub :score ?score .
} WHERE {
  {
    SELECT ?sub ?score ?starts WHERE {
      ?sub <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.archiveshub.ac.uk/def/ArchivalResource> .
      OPTIONAL {
        ?sub <http://www.w3.org/2006/time#intervalStarts> ?starts .
      }
    }
    ORDER BY ?starts ?score
    OFFSET 0
    LIMIT 20
  }
  GRAPH ?g {
    ?sub ?pred ?obj .
  }
}
```

**Comment by l00mi** [comment]
I see, but the order is only destroy inside the 20 results, right?

For the proposed SCORE function this might be of help: https://github.com/zazuko/zack-search/blob/develop/queries/stardog-histogram.sparql#L37

**Comment by bergos** [comment]
Fixed with [this sparql-search-result-list commit](https://github.com/zazukoians/sparql-search-result-list/commit/e31d5e628f31abfd63ca4c2109350953c511f28b) and [this commit for the query](https://github.com/zazuko/zack-search/commit/0702d41843a230b627a8d3ee353c35047da2644c).
